# Generated by Django 3.2 on 2022-02-23 17:29

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=245)),
                ('contact_number', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=8)),
                ('wedding_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(default='designer@bridal-union.com', max_length=245)),
                ('location', models.CharField(max_length=50)),
                ('starting_price', models.FloatField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('image_name', models.CharField(default='name of image', max_length=30)),
                ('image_description', models.TextField(blank=True, null=True)),
                ('hashtags', models.CharField(blank=True, max_length=300, null=True)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Posted')], default=0)),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_marketplace.designer')),
                ('likes', models.ManyToManyField(blank=True, related_name='imagepost_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='ImageComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social_marketplace.imageposts')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(choices=[('£2,500 - £3,500', '£2,500 - £3,500'), ('£3,500 - £4,500', '£3,500 - £4,500'), ('£4,500 - £5,500', '£4,500 - £5,500'), ('£5,500 - £6,500', '£5,500 - £6,500'), ('£6,500 - £7,500', '£6,500 - £7,500'), ('£7,500 - £8,500', '£7,500 - £8,500'), ('£8,500 - £9,500', '£8,500 - £9,500'), ('£9,500 +', '£9,500 +')], default='£2,500 - £3,500', max_length=200)),
                ('customer_message', models.TextField(blank=True, max_length=800)),
                ('booking_created_on_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Confirm Booking', 'Confirm Booking'), ('Decline Booking', 'Decline Booking')], max_length=200)),
                ('booking_ref', models.CharField(editable=False, max_length=8, unique=True)),
                ('customer_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customeremail', to='social_marketplace.customeraccount')),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customername', to='social_marketplace.customeraccount')),
                ('designer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designername', to='social_marketplace.designer')),
            ],
        ),
    ]
