# Generated by Django 3.2 on 2022-02-25 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='wedding_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='wedding_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
