# Generated by Django 3.2 on 2022-02-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_marketplace', '0002_auto_20220215_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Upcoming Bookings', 'Upcoming Bookings'), ('Past Bookings', 'Past Booking')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=245)),
                ('contact_number', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=8)),
                ('budget', models.FloatField()),
                ('wedding_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='imageposts',
            old_name='designer_name',
            new_name='designer',
        ),
        migrations.RemoveField(
            model_name='imageposts',
            name='image_size',
        ),
        migrations.AddField(
            model_name='designer',
            name='email',
            field=models.EmailField(default='designer@bridal-union.com', max_length=245),
        ),
        migrations.AlterField(
            model_name='designer',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='starting_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='imageposts',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Posted')], default=0),
        ),
        migrations.CreateModel(
            name='ImageComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social_marketplace.imageposts')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
