# Generated by Django 3.2 on 2022-02-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_marketplace', '0003_auto_20220219_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_marketplace.customeraccount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_marketplace.designer'),
        ),
    ]
