# Generated by Django 3.2 on 2022-03-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_marketplace', '0003_auto_20220225_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='select_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='select_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
