# Generated by Django 3.2 on 2022-02-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_marketplace', '0004_auto_20220219_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='imageposts',
            name='name',
            field=models.CharField(default='name of image', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirm Bookings', 'Confirm Bookings'), ('Decline Bookings', 'Decline Booking')], max_length=200),
        ),
    ]
