# Generated by Django 3.2 on 2022-06-06 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_marketplace', '0004_auto_20220303_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecomments',
            name='name',
        ),
        migrations.AddField(
            model_name='imagecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
