# Generated by Django 3.2 on 2022-02-21 15:24

import cloudinary.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('social_marketplace', '0006_rename_name_imageposts_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageposts',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[1000, 1000], upload_to=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
        ),
    ]
