# Generated by Django 3.2 on 2022-02-21 15:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_marketplace', '0007_alter_imageposts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageposts',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
