# Generated by Django 3.2 on 2022-06-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_marketplace', '0007_alter_imagecomments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageposts',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
