# Generated by Django 3.2 on 2022-02-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_marketplace', '0008_alter_imageposts_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date_created',
            new_name='booking_created_on_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='starting_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customeremail', to='social_marketplace.customeraccount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_message',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customername', to='social_marketplace.customeraccount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='designer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designername', to='social_marketplace.designer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_range',
            field=models.CharField(choices=[('£2,500 - £3,500', '£2,500 - £3,500'), ('£3,500 - £4,500', '£3,500 - £4,500'), ('£4,500 - £5,500', '£4,500 - £5,500'), ('£5,500 - £6,500', '£5,500 - £6,500'), ('£6,500 - £7,500', '£6,500 - £7,500'), ('£7,500 - £8,500', '£7,500 - £8,500'), ('£8,500 - £9,500', '£8,500 - £9,500'), ('£9,500 +', '£9,500 +')], default='£2,500 - £3,500', max_length=200),
        ),
        migrations.AddField(
            model_name='designer',
            name='price_range',
            field=models.CharField(choices=[('£2,500 - £3,500', '£2,500 - £3,500'), ('£3,500 - £4,500', '£3,500 - £4,500'), ('£4,500 - £5,500', '£4,500 - £5,500'), ('£5,500 - £6,500', '£5,500 - £6,500'), ('£6,500 - £7,500', '£6,500 - £7,500'), ('£7,500 - £8,500', '£7,500 - £8,500'), ('£8,500 - £9,500', '£8,500 - £9,500'), ('£9,500 +', '£9,500 +')], default='£2,500 - £3,500', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirm Booking', 'Confirm Booking'), ('Decline Booking', 'Decline Booking')], max_length=200),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='budget',
            field=models.CharField(choices=[('£2,500 - £3,500', '£2,500 - £3,500'), ('£3,500 - £4,500', '£3,500 - £4,500'), ('£4,500 - £5,500', '£4,500 - £5,500'), ('£5,500 - £6,500', '£5,500 - £6,500'), ('£6,500 - £7,500', '£6,500 - £7,500'), ('£7,500 - £8,500', '£7,500 - £8,500'), ('£8,500 - £9,500', '£8,500 - £9,500'), ('£9,500 +', '£9,500 +')], default='£2,500 - £3,500', max_length=200),
        ),
    ]
