# Generated by Django 3.2 on 2022-02-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_marketplace', '0009_auto_20220223_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='price_range',
        ),
        migrations.AddField(
            model_name='designer',
            name='starting_price',
            field=models.FloatField(default='£2,500'),
        ),
    ]
