# Generated by Django 3.2 on 2022-02-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_marketplace', '0010_auto_20220223_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='starting_price',
            field=models.FloatField(default='None'),
        ),
    ]
