# Generated by Django 3.2 on 2022-02-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_marketplace', '0011_alter_designer_starting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='starting_price',
            field=models.FloatField(default=0),
        ),
    ]
