# Generated by Django 3.2 on 2022-06-07 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_marketplace', '0011_auto_20220607_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomments',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social_marketplace.imageposts'),
        ),
    ]
