# Generated by Django 3.2 on 2022-06-06 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_marketplace', '0005_auto_20220606_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(choices=[('£2,500 - £3,500', '£2,500 - £3,500'), ('£3,500 - £4,500', '£3,500 - £4,500'), ('£4,500 - £5,500', '£4,500 - £5,500'), ('£5,500 - £6,500', '£5,500 - £6,500'), ('£6,500 - £7,500', '£6,500 - £7,500'), ('£7,500 - £8,500', '£7,500 - £8,500'), ('£8,500 - £9,500', '£8,500 - £9,500'), ('£9,500 +', '£9,500 +')], default='£2,500 - £3,500', max_length=200)),
                ('wedding_date', models.DateField(auto_now=True)),
                ('select_date', models.DateField(auto_now=True)),
                ('select_time', models.DateTimeField(auto_now=True)),
                ('customer_message', models.TextField(blank=True, max_length=800)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('Confirm Booking', 'Confirm Booking'), ('Decline Booking', 'Decline Booking')], max_length=200)),
                ('customer_email', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customeremail', to=settings.AUTH_USER_MODEL)),
                ('customer_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customername', to=settings.AUTH_USER_MODEL)),
                ('designer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designername', to='social_marketplace.designer')),
            ],
        ),
    ]
