# Generated by Django 3.2 on 2022-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='select_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='requested_time',
            field=models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00')], default='12:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='select_date',
            field=models.DateField(),
        ),
    ]
